app-id: org.mavlink.qgroundcontrol
runtime: org.kde.Platform
runtime-version: "6.7"
sdk: org.kde.Sdk
command: QGroundControl
rename-appdata-file: org.mavlink.qgroundcontrol.metainfo.xml

finish-args:
  - --socket=wayland
  - --socket=fallback-x11
  - --socket=pulseaudio
  - --device=all # allow access USB Serial
  - --share=ipc
  - --share=network
  - --filesystem=home
  - --filesystem=xdg-run/gvfs # GVfs
  - --filesystem=/media # automount via udisks
  - --filesystem=/run/udev:ro # enables firmware upload & auto connecting

build-options:
  build-args:
  - "--share=network"

modules:
  - name: QGroundControl
    sources:
      - type: git
        url: https://github.com/mavlink/qgroundcontrol.git
        commit: 2aefff18582141bebba650a0d033f8c9a5d3457c
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -D BUILD_SHARED_LIBS=OFF
      - -D OpenGL_GL_PREFERENCE=GLVND
      - -D BUILD_TESTING=OFF
    cleanup:
      - /include
      - /bin/dbf*
      - /bin/shp*
      - /lib/cmake
      - /share/shapelib
      - '*.a'
      - '*.cmake'
