set(QGC_APP_NAME "ZATQGC" CACHE STRING "Application Name" FORCE)

set(QGC_DISABLE_APM_PLUGIN_FACTORY ON CACHE BOOL "Disable APM Plugin Factory" FORCE)

set(QGC_DISABLE_PX4_PLUGIN ON CACHE BOOL "Disable PX4 Plugin" FORCE)
set(QGC_DISABLE_PX4_PLUGIN_FACTORY ON CACHE BOOL "Disable PX4 Plugin Factory" FORCE)
