message(STATUS "Creating AppImage")

set(APPDIR_PATH "${CMAKE_BINARY_DIR}/AppDir")
set(LD_PATH "${CMAKE_BINARY_DIR}/linuxdeploy-x86_64.AppImage")
set(LD_APPIMAGE_PLUGIN_PATH "${CMAKE_BINARY_DIR}/linuxdeploy-plugin-appimage-x86_64.AppImage")
set(LD_QT_PLUGIN_PATH "${CMAKE_BINARY_DIR}/linuxdeploy-plugin-qt-x86_64.AppImage")
set(LD_GSTREAMER_PLUGIN_PATH "${CMAKE_BINARY_DIR}/linuxdeploy-plugin-gstreamer.sh")

if(NOT EXISTS "${LD_PATH}")
    file(DOWNLOAD https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage "${LD_PATH}")
    execute_process(COMMAND chmod a+x "${LD_PATH}")
endif()
if(NOT EXISTS "${LD_APPIMAGE_PLUGIN_PATH}")
    file(DOWNLOAD https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage "${LD_APPIMAGE_PLUGIN_PATH}")
    execute_process(COMMAND chmod a+x "${LD_APPIMAGE_PLUGIN_PATH}")
endif()
if(NOT EXISTS "${LD_QT_PLUGIN_PATH}")
    file(DOWNLOAD https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage "${LD_QT_PLUGIN_PATH}")
    execute_process(COMMAND chmod a+x "${LD_QT_PLUGIN_PATH}")
endif()
if(NOT EXISTS "${LD_GSTREAMER_PLUGIN_PATH}")
    file(DOWNLOAD https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gstreamer/master/linuxdeploy-plugin-gstreamer.sh "${LD_GSTREAMER_PLUGIN_PATH}")
    execute_process(COMMAND chmod a+x "${LD_GSTREAMER_PLUGIN_PATH}")
endif()
execute_process(COMMAND ${LD_PATH} --appdir ${APPDIR_PATH} --output appimage) # --plugin qt # --plugin gstreamer
