name: Android-MacOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    strategy:
      matrix:
        BuildType: [Debug, Release]

    defaults:
      run:
        shell: bash

    env:
      ARTIFACT: QGroundControl.apk
      QT_VERSION: 6.6.3
      GST_VERSION: 1.22.12
      QT_ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/deploy/android/android_release.keystore
      QT_ANDROID_KEYSTORE_ALIAS: QGCAndroidKeyStore
      QT_ANDROID_KEYSTORE_STORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      QT_ANDROID_KEYSTORE_KEY_PASS: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      QT_ANDROID_ABIS: "armeabi-v7a;arm64-v8a"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-tags: true
          fetch-depth: 0

      # Temporary solution
      - name: Remove unused dependencies
        run: rm -rf libs

      - name: Setup Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Dependencies
        run: |
          brew update
          brew install cmake ninja ccache

      - name: Set Up Cache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-Android-${{ matrix.BuildType }}
          restore-keys: ${{ runner.os }}-Android-${{ matrix.BuildType }}
          max-size: 1G
          append-timestamp: false
          save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Install Qt for MacOS
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          aqtversion: ==3.1.*
          host: mac
          target: desktop
          dir: ${{ runner.temp }}
          modules: qtcharts qtlocation qtpositioning qtspeech qt5compat qtmultimedia qtserialport qtimageformats qtshadertools qtconnectivity qtquick3d qtsensors
          cache: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Install Qt for Android (armv7)
        uses: jurplel/install-qt-action@v4
        if: contains( env.QT_ANDROID_ABIS, 'armeabi-v7a')
        with:
          version: ${{ env.QT_VERSION }}
          aqtversion: ==3.1.*
          host: mac
          target: android
          arch: android_armv7
          dir: ${{ runner.temp }}
          extra: --autodesktop
          modules: qtcharts qtlocation qtpositioning qtspeech qt5compat qtmultimedia qtserialport qtimageformats qtshadertools qtconnectivity qtquick3d qtsensors
          cache: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Install Qt for Android (arm64_v8a)
        uses: jurplel/install-qt-action@v4
        if: contains( env.QT_ANDROID_ABIS, 'arm64-v8a')
        with:
          version: ${{ env.QT_VERSION }}
          aqtversion: ==3.1.*
          host: mac
          target: android
          arch: android_arm64_v8a
          dir: ${{ runner.temp }}
          extra: --autodesktop
          modules: qtcharts qtlocation qtpositioning qtspeech qt5compat qtmultimedia qtserialport qtimageformats qtshadertools qtconnectivity qtquick3d qtsensors
          cache: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Install Qt for Android (x86)
        uses: jurplel/install-qt-action@v4
        if: contains( env.QT_ANDROID_ABIS, 'x86')
        with:
          version: ${{ env.QT_VERSION }}
          aqtversion: ==3.1.*
          host: mac
          target: android
          arch: android_x86
          dir: ${{ runner.temp }}
          extra: --autodesktop
          modules: qtcharts qtlocation qtpositioning qtspeech qt5compat qtmultimedia qtserialport qtimageformats qtshadertools qtconnectivity qtquick3d qtsensors
          cache: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Install Qt for Android (x86_64)
        uses: jurplel/install-qt-action@v4
        if: contains( env.QT_ANDROID_ABIS, 'x86_64')
        with:
          version: ${{ env.QT_VERSION }}
          aqtversion: ==3.1.*
          host: mac
          target: android
          arch: android_x86_64
          dir: ${{ runner.temp }}
          extra: --autodesktop
          modules: qtcharts qtlocation qtpositioning qtspeech qt5compat qtmultimedia qtserialport qtimageformats qtshadertools qtconnectivity qtquick3d qtsensors
          cache: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - run: mkdir ${{ runner.temp }}/shadow_build_dir

      - name: Configure
        working-directory: ${{ runner.temp }}/shadow_build_dir
        run: ${{ env.QT_ROOT_DIR }}/bin/qt-cmake -S ${{ github.workspace }} -B . -G Ninja
              -DCMAKE_BUILD_TYPE=${{ matrix.BuildType }}
              -DQT_ANDROID_ABIS="${{ env.QT_ANDROID_ABIS }}"
              -DQT_ANDROID_BUILD_ALL_ABIS=OFF
              -DQT_HOST_PATH="${{ env.QT_ROOT_DIR }}/../msvc2019_64"
              -DQT_ANDROID_SIGN_APK=${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && 'ON' || 'OFF' }}
              -DQT_DEBUG_FIND_PACKAGE=ON
              -DQGC_STABLE_BUILD=${{ github.ref_type == 'tag' || contains(github.ref, 'Stable') && 'ON' || 'OFF' }}

      - name: Build
        working-directory: ${{ runner.temp }}/shadow_build_dir
        run: cmake --build . --target all --config ${{ matrix.BuildType }}

      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}/shadow_build_dir/android-build/*.apk
