name: Custom build

# Build custom QGroundControl variant

on:
  push:
    branches:
      - master
      - Stable*
    tags:
      - v*
    paths-ignore:
      - docs/**
  pull_request:
    paths:
      - .github/workflows/custom.yml
      - .github/actions/**
      - deploy/windows/**
      - src/**
      - custom-example/**
      - CMakeLists.txt
      - cmake/**
      - tools/setup/*windows*
  workflow_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.ref_type != 'tag' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 120

    defaults:
      run:
        shell: cmd

    env:
      QT_VERSION: 6.10.0
      GST_VERSION: 1.22.12

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: ${{ github.ref_type == 'tag' && 0 || 1 }}
          fetch-tags: true

      - name: Initial Setup
        uses: ./.github/actions/common

      - name: Enable custom build
        run: |
          if not exist ".\custom-example" (
            echo Directory ".\custom-example" does not exist. && exit /b 1
          )
          xcopy /E /I ".\custom-example" ".\custom"

      - name: Install GStreamer
        uses: blinemedical/setup-gstreamer@v1
        with:
          version: ${{ env.GST_VERSION }}

      - name: Setup Caching
        uses: ./.github/actions/cache
        with:
          host: windows
          target: win64_msvc2022_64
          build-type: Release
          cpm-modules: ${{ runner.temp }}\build\cpm_modules

      - name: Install Qt
        uses: ./.github/actions/qt-install
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          dir: ${{ runner.temp }}

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        working-directory: ${{ runner.temp }}\build
        run: |
          ${{ env.QT_ROOT_DIR }}/bin/qt-cmake -S ${{ github.workspace }} -B . -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DQGC_STABLE_BUILD=${{ github.ref_type == 'tag' || contains(github.ref, 'Stable') && 'ON' || 'OFF' }}

      - name: Build
        shell: bash
        working-directory: ${{ runner.temp }}\build
        run: |
          BUILD_START_TIME=$(date +%s)
          cmake --build . --target all --config Release --parallel
          BUILD_END_TIME=$(date +%s)
          BUILD_DURATION=$((BUILD_END_TIME - BUILD_START_TIME))
          echo "Build completed in ${BUILD_DURATION} seconds"
          echo "BUILD_DURATION=${BUILD_DURATION}" >> $GITHUB_ENV

      - name: Verify executable
        working-directory: ${{ runner.temp }}\build\Release
        run: Custom-QGroundControl.exe --simple-boot-test
