name: Docker-Linux

# Build QGroundControl using Docker container

on:
  push:
    branches:
      - master
      - 'Stable*'
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths:
      - '.github/workflows/docker-linux.yml'
      - '.github/actions/**'
      - 'deploy/docker/**'
      - 'deploy/linux/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
  workflow_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.ref_type != 'tag' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: ${{ github.ref_type == 'tag' && 0 || 1 }}
          fetch-tags: true

      - name: Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: git fetch --all --tags --force --depth 1

      - run: chmod a+x ./deploy/docker/run-docker-ubuntu.sh

      - name: Run Docker Build
        run: ./deploy/docker/run-docker-ubuntu.sh
