name: MacOS

# Build, sign, and notarize QGroundControl for macOS

on:
  push:
    branches:
      - master
      - 'Stable*'
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**' # Do not trigger for any changes under docs
  pull_request:
    paths:
      - '.github/workflows/macos.yml'
      - '.github/actions/**'
      - 'deploy/macos/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
  workflow_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.ref_type != 'tag' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 120

    strategy:
      matrix:
        build_type: [Release]

    defaults:
      run:
        shell: bash

    env:
      QT_VERSION: 6.10.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: ${{ github.ref_type == 'tag' && 0 || 1 }}
          fetch-tags: true

      - name: Initial Setup
        uses: ./.github/actions/common

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '<=16.x'

      - name: Install Dependencies (include GStreamer)
        working-directory: ${{ github.workspace }}/tools/setup
        run: sh install-dependencies-osx.sh

      - name: Setup Caching
        uses: ./.github/actions/cache
        with:
          host: mac
          target: clang_64
          build-type: ${{ matrix.build_type }}
          cpm-modules: ${{ runner.temp }}/build/cpm_modules

      - name: Install Qt
        uses: ./.github/actions/qt-install
        with:
          version: ${{ env.QT_VERSION }}
          host: mac
          target: desktop
          arch: clang_64
          dir: ${{ runner.temp }}

      - name: CMake configure
        working-directory: ${{ runner.temp }}/build
        run: ${{ env.QT_ROOT_DIR }}/bin/qt-cmake -S ${{ github.workspace }} -B . -G Ninja
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
              -DQGC_STABLE_BUILD=${{ github.ref_type == 'tag' || contains(github.ref, 'Stable') && 'ON' || 'OFF' }}
              -DQGC_MACOS_SIGN_WITH_IDENTITY=${{ github.event_name != 'pull_request' && 'ON' || 'OFF' }}

      - name: Build
        working-directory: ${{ runner.temp }}/build
        run: |
          BUILD_START_TIME=$(date +%s)
          cmake --build . --target all --config ${{ matrix.build_type }} --parallel
          BUILD_END_TIME=$(date +%s)
          BUILD_DURATION=$((BUILD_END_TIME - BUILD_START_TIME))
          echo "Build completed in ${BUILD_DURATION} seconds"
          echo "BUILD_DURATION=${BUILD_DURATION}" >> $GITHUB_ENV

      - name: Sanity check dev build executable
        working-directory: ${{ runner.temp }}/build/Release/QGroundControl.app/Contents/MacOS
        run: ./QGroundControl --simple-boot-test

      - name: Import Code Signing Certificate
        if: github.event_name != 'pull_request'
        uses: apple-actions/import-codesign-certs@v5
        with:
          p12-file-base64: ${{ secrets.MACOS_CERT_P12_BASE64 }}
          p12-password: ${{ secrets.MACOS_CERT_P12_PASSWORD }}

      - name: Create signed/notarized/stapled app bundle
        working-directory: ${{ runner.temp }}/build
        run: cmake --install . --config ${{ matrix.build_type }}
        env:
          QGC_MACOS_SIGNING_IDENTITY: ${{ secrets.MACOS_SIGNING_IDENTITY }}
          QGC_MACOS_NOTARIZATION_USERNAME: ${{ secrets.MACOS_NOTARIZATION_USERNAME }}
          QGC_MACOS_NOTARIZATION_PASSWORD: ${{ secrets.MACOS_NOTARIZATION_PASSWORD }}
          QGC_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}

      - name: Mount DMG
        working-directory: ${{ runner.temp }}/build
        run: hdiutil attach QGroundControl.dmg

      - name: Sanity check DMG executable
        working-directory: /Volumes/QGroundControl/QGroundControl.app/Contents/MacOS
        run: ./QGroundControl --simple-boot-test

      - name: Upload Build File
        if: matrix.build_type == 'Release'
        uses: ./.github/actions/upload
        permissions:
          contents: write
        with:
          artifact_name: QGroundControl.dmg
          package_name: QGroundControl
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_distribution_id: ${{ secrets.AWS_DISTRIBUTION_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          retention-days: ${{ github.ref_type == 'tag' && 90 || 7 }}
