name: 'Handle stale issues and PRs'

# Mark stale issues and PRs after 30 days of inactivity

on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/stale@v10
        with:
          days-before-stale: 30
          days-before-close: -1
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          remove-stale-when-updated: true
